
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.4/Modules/CMakeDetermineSystem.cmake:218 (message)"
      - "CMakeLists.txt:15 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
  -
    kind: "find-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.4/Modules/FindPython/Support.cmake:2631 (find_program)"
      - "C:/Program Files/CMake/share/cmake-4.4/Modules/FindPython.cmake:728 (include)"
      - "CMakeLists.txt:30 (find_package)"
    mode: "program"
    variable: "_Python_EXECUTABLE_DEBUG"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "python3.13_d"
      - "python3_d"
      - "python_d"
    candidate_directories:
      - "C:/Users/\uae40\uc601\uae30/.openclaw/workspace/projects/coopagent/.venv/Scripts/"
    searched_directories:
      - "C:/Users/\uae40\uc601\uae30/.openclaw/workspace/projects/coopagent/.venv/Scripts/python3.13_d.com"
      - "C:/Users/\uae40\uc601\uae30/.openclaw/workspace/projects/coopagent/.venv/Scripts/python3.13_d.exe"
      - "C:/Users/\uae40\uc601\uae30/.openclaw/workspace/projects/coopagent/.venv/Scripts/python3.13_d"
      - "C:/Users/\uae40\uc601\uae30/.openclaw/workspace/projects/coopagent/.venv/Scripts/python3_d.com"
      - "C:/Users/\uae40\uc601\uae30/.openclaw/workspace/projects/coopagent/.venv/Scripts/python3_d.exe"
      - "C:/Users/\uae40\uc601\uae30/.openclaw/workspace/projects/coopagent/.venv/Scripts/python3_d"
      - "C:/Users/\uae40\uc601\uae30/.openclaw/workspace/projects/coopagent/.venv/Scripts/python_d.com"
      - "C:/Users/\uae40\uc601\uae30/.openclaw/workspace/projects/coopagent/.venv/Scripts/python_d.exe"
      - "C:/Users/\uae40\uc601\uae30/.openclaw/workspace/projects/coopagent/.venv/Scripts/python_d"
    found: false
    search_context:
      ENV{PATH}:
        - "C:\\Users\\\uae40\uc601\uae30\\.openclaw\\workspace\\projects\\coopagent\\.venv\\Scripts"
        - "c:\\Users\\\uae40\uc601\uae30\\AppData\\Roaming\\Code\\User\\globalStorage\\github.copilot-chat\\debugCommand"
        - "c:\\Users\\\uae40\uc601\uae30\\AppData\\Roaming\\Code\\User\\globalStorage\\github.copilot-chat\\copilotCli"
        - "C:\\Program Files\\Common Files\\Oracle\\Java\\javapath"
        - "C:\\Program Files\\Python313\\Scripts\\"
        - "C:\\Program Files\\Python313\\"
        - "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.9\\bin"
        - "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.9\\libnvvp"
        - "C:\\Windows\\system32"
        - "C:\\Windows"
        - "C:\\Windows\\System32\\Wbem"
        - "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\"
        - "C:\\Windows\\System32\\OpenSSH\\"
        - "C:\\Program Files\\NVIDIA Corporation\\Nsight Compute 2025.2.0\\"
        - "C:\\Program Files\\NVIDIA Corporation\\NVIDIA App\\NvDLISR"
        - "C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common"
        - "C:\\Program Files\\dotnet\\"
        - "C:\\Program Files\\Pandoc\\"
        - "C:\\Program Files\\nodejs\\"
        - "C:\\Program Files\\GitHub CLI\\"
        - "C:\\Program Files\\CMake\\bin"
        - "C:\\Program Files\\Tailscale\\"
        - "C:\\Program Files\\Common Files\\Oracle\\Java\\javapath"
        - "C:\\Program Files\\Python313\\Scripts\\"
        - "C:\\Program Files\\Python313\\"
        - "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.9\\bin"
        - "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.9\\libnvvp"
        - "C:\\Windows\\system32"
        - "C:\\Windows"
        - "C:\\Windows\\System32\\Wbem"
        - "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\"
        - "C:\\Windows\\System32\\OpenSSH\\"
        - "C:\\Program Files\\NVIDIA Corporation\\Nsight Compute 2025.2.0\\"
        - "C:\\Program Files\\NVIDIA Corporation\\NVIDIA App\\NvDLISR"
        - "C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common"
        - "C:\\Program Files (x86)\\Windows Kits\\10\\Windows Performance Toolkit\\"
        - "C:\\Program Files\\dotnet\\"
        - "C:\\Program Files\\Pandoc\\"
        - "C:\\Program Files\\nodejs\\"
        - "C:\\Users\\\uae40\uc601\uae30\\AppData\\Local\\Microsoft\\WindowsApps"
        - "C:\\Users\\\uae40\uc601\uae30\\AppData\\Local\\Programs\\Ollama"
        - "C:\\Users\\\uae40\uc601\uae30\\AppData\\Local\\Programs\\Microsoft VS Code\\bin"
        - "C:\\Users\\\uae40\uc601\uae30\\AppData\\Roaming\\npm"
        - "C:\\Users\\\uae40\uc601\uae30\\AppData\\Local\\OpenClaw\\deps\\portable-node"
        - "C:\\Users\\\uae40\uc601\uae30\\AppData\\Local\\OpenClaw\\deps\\portable-git\\mingw64\\bin"
        - "C:\\Users\\\uae40\uc601\uae30\\AppData\\Local\\OpenClaw\\"
        - "C:\\Users\\\uae40\uc601\uae30\\.dotnet\\tools"
        - "C:\\Users\\\uae40\uc601\uae30\\Ninja"
        - "C:\\Users\\\uae40\uc601\uae30\\AppData\\Local\\Microsoft\\WindowsApps"
        - "C:\\msys64\\ucrt64\\bin"
        - "C:\\msys64\\clang64\\bin"
        - "C:\\Users\\\uae40\uc601\uae30\\AppData\\Local\\Google\\Cloud SDK\\google-cloud-sdk\\bin"
        - "c:\\Users\\\uae40\uc601\uae30\\.vscode\\extensions\\ms-python.debugpy-2026.6.0-win32-x64\\bundled\\scripts\\noConfigScripts"
      CMAKE_INSTALL_PREFIX: "C:/Program Files/documentation-agent"
      CMAKE_SYSTEM_PREFIX_PATH:
        - "C:/Program Files"
        - "C:/Program Files (x86)"
        - "C:/Program Files/CMake"
        - "C:/Program Files/documentation-agent"
...
